---
language: go
sudo: false
go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
